import '~/styles/globals.css';
import type { Metadata } from 'next';
import Header from '~/components/Header/Header';
import { jetBrainsMono } from '~/fonts/font.config';
import PageTransition from '~/components/transitions/TransitionPage';
import StairsTransition from '~/components/transitions/StairsTransition';

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={jetBrainsMono.variable}>
            <Header />
            <StairsTransition />
            <PageTransition>{children}</PageTransition>
         </body>
      </html>
   );
}
