import type { Metadata } from "next";
import "./globals.css";
import styles from "./main.module.css";
import clsx from "clsx";
import Header from "~/components/Header";
import { spaceMono } from "~/fonts/font.config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <div className="">
          <Header />
          {/* <div className={.content}></div> */}
          {children}
        </div>
      </body>
    </html>
  );
}
