import type { Metadata } from "next";
import "./globals.css";
import Header from "~/components/Header/Header";
import { jetBrainsMono } from "~/fonts/font.config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable}>
        <Header />
        {children}
      </body>
    </html>
  );
}
